server:
  port: 8081
  address: 127.0.0.1

spring:
  application:
    name: auth-server
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:demo_db
    username: root
    password:
  database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true